### ISSUE TITLE
点击最大化按钮后在点击不能还原了。

### ISSUE THREAD

**Issue by lzh1104** [o2team/xcel#10]
点击最大化按钮后在点击不能还原了。
报错如图
![1286bf25-db7f-4f35-adca-6ef1a684565a](https://user-images.githubusercontent.com/663128/27531494-656334ee-5a8f-11e7-95e6-35efbf388de3.png)

**Comment by JChehe** [comment]
@lzh1104 已解决： 5375ef9659be6d5e0956758f380cdbf0ffef949e

问题原因：   
与 new BrowserWindow 初始化时不同（忽略x、y时会自动居中），setBounds 需要明确指定 x、y。
