### ISSUE TITLE
运行dev的时候报错

### ISSUE THREAD

**Issue by huanglei1991** [o2team/xcel#2]
![image](https://cloud.githubusercontent.com/assets/25176774/22079639/8f6913d6-ddf7-11e6-8750-4b02b839d076.png)
你们开发都是用什么系统我  我win10 node6.9.4
是不是 win系统下的例子都很难运行 这几天遇到很多次win问题了

**Comment by JChehe** [comment]
@huanglei1991 Sorry，按照报错提示，的确是 app 目录下的 `package.json` 缺少了 `fs-extra` 依赖。
你可以在 `xcel/app` 目录下， `npm install --save fs-extra`。（现已修正）

我现在是用 macOS 进行开发的。讲真，我也是从这个项目开始使用 macOS 的😭。用着用着觉得还挺好用的（习惯了）。

至于[是不是 win 系统下的例子都很难运行]，有很多因素决定吧，例如网络问题等。
