### ISSUE TITLE
项目的介绍图看不清楚

### ISSUE THREAD

**Issue by hahazexia** [o2team/xcel#3]
介绍页面下面有一个项目结构的截图，但是好模糊啊，看不清楚，麻烦作者能更新一下吗？
最近在学习electron和vue相关的知识，多谢了!

**Comment by JChehe** [comment]
@hahazexia 你点击图片就会在新的标签页显示，这样就比较清晰了。

另外，关于 Electron 的介绍可以看看这篇 https://aotu.io/notes/2016/11/15/xcel/ ，对 Electron 有个整体的认识。

也可以看看这个，看看 Electron 提供了什么功能：https://github.com/electron/electron-api-demos

vue 的话，可以结合已有 API（如 CNode 提供的 API https://cnodejs.org/api）实现一个 vue 版本应用。

**Comment by hahazexia** [comment]
@JChehe 恩，好的，可能公司网络有些问题，我回家再试试，多谢

**Comment by JChehe** [comment]
@hahazexia 因为README.md 里的图自动上传到github上，导致图片加载有问题。    
原图你可以到 https://github.com/o2team/misc/tree/gh-pages/JChehe/2016-11-15-xcel 这里下载。
