### ISSUE TITLE
导入文件格式不对  提示信息出现后  loading没有去掉  一直在转  无法继续操作

### ISSUE THREAD

**Issue by FantasticPerson** [o2team/xcel#5]
导入文件格式不对  提示信息出现后  loading没有去掉  一直在转  无法继续操作

**Comment by JChehe** [comment]
@wdd119 OK, 收到。
目前你可以通过快捷键  `ctrl/command + r` 进行重载刷新。

**Comment by JChehe** [comment]
@wdd119 v1.3.1 增加了对导入文件的限制了
https://github.com/o2team/xcel/releases/tag/v1.3.1
