### ISSUE TITLE
卡在了webpack: Compiled with warnings.

### ISSUE THREAD

**Issue by shmilyoo** [o2team/xcel#6]
ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-3ad00e41!./~/vue-loader/lib/selector.js?type=template&index=0!./app/src/components/InstructionsPageView/Instructions.vue
         template syntax error tag <strong> has no matching end tag.
         
         ERROR in ./~/vue-loader/lib/template-compiler.js?id=data-v-17a588f9!./~/vue-loader/lib/selector.js?type=template&index=0!./app/src/components/FirstScreenPageView/FilterFormMultiCalc.vue
         template syntax error tag <span> has no matching end tag.

把这两个文件的tag补全后，npm run dev，最后一行是
webpack: Compiled with warnings.
然后没有反应了。不出来界面。npm安装依赖没有问题

**Comment by JChehe** [comment]
@shmilyoo 正如报错的提示：`Instructions.vue` 和 `FilterFormMultiCalc.vue` 两个组件的模板 `template` 存在语法错误——\<strong\>/\<span\> 两个标签没有对应的 \</strong\>/\</span\> 结尾标签。

现在提交修复好了，你`git pull`拉取最新代码后应该可以了。

最后，感谢你的issues。

**Comment by shmilyoo** [comment]
@JChehe npm run dev 后，卡在了webpack: Compiled with warnings. 这一行，应用界面没有出现，我安装依赖没有问题。只有一堆warning，没有error出现。

**Comment by JChehe** [comment]
@shmilyoo Hello，我更新依赖后也出现你的问题。现在解决了。  

 1. 对于 warnings：是`request` 和 `xlsx` 模块版本问题。     
 2. 对于应用没启动（无应用界面）：应该也是模块更新后导致启动应用的相应命令失效。现在修改了 `tasks/runner.js` 的相应启动 electron 应用的代码了。
